(library
 (name xix_commons)
 (wrapped false)
 ; no Fpath below! we can't use the local Fpath.ml because we also want
 ; to use Testo in ../tests/, which is relying on the OPAM Fpath, so we
 ; would get linking errors if we were using our own Fpath.ml so we must find a
 ; way to remain forward compatible.
 ; we now also skip Logs.ml; Testo is not using it so we're fine
 ; for now by providing our own Logs.ml but we get errors in c-- project
 ; coupling: mkfile SRC variable
 (modules
  Set_ Map_
  Eq Ord
  Common
  Dumper OCaml
  Console
  Logs_ ; Nope: Logs
  Exit Exception
  Chan FS IO Tmp
  Cmd Proc
  Date Bits Rune Bits_of_float
  Fpath_ ; Nope: Fpath ; Ftype (use of =~)
  Arg_
  Arch OS Endian
 )   
 (libraries
    ; stdcompat
    fpath logs
    caps
  )
 (preprocess (pps ppx_deriving.show))
)
